// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmtKUKAT6mgZqRtECbhpYsXS85E5M3HtU',
    appId: '1:871396244997:web:3991fcdd0d367198c2e66c',
    messagingSenderId: '871396244997',
    projectId: 'ai-study-assistant-d1bdf',
    authDomain: 'ai-study-assistant-d1bdf.firebaseapp.com',
    storageBucket: 'ai-study-assistant-d1bdf.firebasestorage.app',
    measurementId: 'G-7LNGZ05L8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaGnlK1EpICe5vax3ub7tf_U8z_RWvW9o',
    appId: '1:871396244997:android:b76de6a08f11b72bc2e66c',
    messagingSenderId: '871396244997',
    projectId: 'ai-study-assistant-d1bdf',
    storageBucket: 'ai-study-assistant-d1bdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuTp5sZcXJMpgOfiqgwnlrBW8j_FVtMJU',
    appId: '1:871396244997:ios:4eef827010973bfbc2e66c',
    messagingSenderId: '871396244997',
    projectId: 'ai-study-assistant-d1bdf',
    storageBucket: 'ai-study-assistant-d1bdf.firebasestorage.app',
    iosBundleId: 'com.example.aiStudyAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuTp5sZcXJMpgOfiqgwnlrBW8j_FVtMJU',
    appId: '1:871396244997:ios:4eef827010973bfbc2e66c',
    messagingSenderId: '871396244997',
    projectId: 'ai-study-assistant-d1bdf',
    storageBucket: 'ai-study-assistant-d1bdf.firebasestorage.app',
    iosBundleId: 'com.example.aiStudyAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmtKUKAT6mgZqRtECbhpYsXS85E5M3HtU',
    appId: '1:871396244997:web:070a47c1fa2263f2c2e66c',
    messagingSenderId: '871396244997',
    projectId: 'ai-study-assistant-d1bdf',
    authDomain: 'ai-study-assistant-d1bdf.firebaseapp.com',
    storageBucket: 'ai-study-assistant-d1bdf.firebasestorage.app',
    measurementId: 'G-YKQM8WYFYH',
  );
}
